### ISSUE TITLE
TypeError: ohmyfetch_1.$fetch.create is not a function

### ISSUE THREAD

**Issue by m0dch3n** [unjs/ohmyfetch#96]
It seems that the build in package of `version '0.4.18` is not correct.

By running my code, I get the error:

`TypeError: ohmyfetch_1.$fetch.create is not a function`

So I looked under node_modules, to find out, that `cjs/node.cjs`

```javascript
const getExport = name => import('../dist/node.mjs').then(r => r[name])
const createCaller = name => (input, init) => getExport(name).then(fn => fn(input, init))

exports.fetch = createCaller('fetch')
exports.$fetch = createCaller('$fetch')
exports.$fetch.raw = (input, init) => getExport('$fetch').then($fetch => $fetch.raw(input, init))
```

needs to include the export of the `create` method...

```javascript
exports.$fetch.create = (defaults) => getExport('$fetch').then($fetch => $fetch.create(defaults))
```

This line was missing, so I added it manually. Now my code runs without any issue in my node environment.

PS: I haven't tried other versions of ohmyfetch...

**Comment by m0dch3n** [comment]
I created a pull request. As I did the fix in the browser with Github, it unfortunately has 3 commits, because you can only edit one file after another on github.com...
